services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: robots
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  rabbit:     ### http://localhost:15672
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: some_user
      RABBITMQ_DEFAULT_PASS: some_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitdata: